### ISSUE TITLE
想问下src下的lib目录是不是重复了？

### ISSUE THREAD

**Issue by catchonme** [palmg/pwfe-server#7]
我看主目录有`lib`文件夹，但是`src`也有，而且文件内容几乎是重复的，想问下如果不是，是基于什么理由呢？

**Comment by chkui** [comment]
不好意思，这么久才回复你问题。src里的是开发版本，是ES5的编码，lib里的是babel编译之后的代码，可以支持大部分浏览器和nodejs8之前的版本。

**Comment by catchonme** [comment]
没事的，感谢感谢！
